# Copyright 2025 Dell Inc. or its subsidiaries. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
---

- name: Set variables for omnia run tags
  hosts: localhost
  connection: local
  tasks:
    - name: Set dynamic run tags for omnia flow
      ansible.builtin.set_fact:
        omnia_run_tags: "{{ (ansible_run_tags | default([]) + ['freeipa'] + ['openldap'] + ['security'] + ['slurm'] + ['storage']) | unique }}"
        cacheable: true
      when: not (config_file_status | default(false) | bool)

    - name: Set fact for compute k8s playbook
      ansible.builtin.set_fact:
        compute_k8s_playbook: true

- name: Invoke validate_config.yml to perform L1 and L2 validations
  ansible.builtin.import_playbook: input_validation/validate_config.yml

- name: Invoke get_config_credentials.yml
  ansible.builtin.import_playbook: utils/credential_utility/get_config_credentials.yml
  when: not (config_file_status | default(false) | bool)

- name: Check if package manager is not locked
  ansible.builtin.import_playbook: utils/check_package_lock.yml
  when: not (apt_lock_status | default(false) | bool)

- name: Include input project directory
  ansible.builtin.import_playbook: utils/include_input_dir.yml
  when: not (project_dir_status | default(false) | bool)

- name: Update Inventory with ansible_host information
  ansible.builtin.import_playbook: utils/servicetag_host_mapping.yml
  when: not (update_inventory_executed | default(false) | bool)

- name: Validate inventory
  ansible.builtin.import_playbook: utils/inventory_validation.yml
  when: not (inventory_validation_executed | default(false) | bool)

- name: Set flag
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: Set flag to indicate check_package_lock.yml has been executed
      ansible.builtin.set_fact:
        apt_lock_status: true

- name: Gather facts from all the nodes
  hosts: slurm_control_node, slurm_node, login, kube_control_plane, kube_node, etcd, auth_server
  gather_facts: true

- name: Validate all input parameters
  hosts: localhost
  connection: local
  gather_facts: true
  roles:
    - role: scheduler/roles/cluster_validation     # noqa:role-name[path]
    - role: security/roles/security_validation     # noqa:role-name[path]
    - role: storage/roles/storage_validation       # noqa:role-name[path]
#    - role: telemetry/roles/telemetry_validation   # noqa:role-name[path]

- name: Update Repositories/Registries on nodes
  ansible.builtin.import_playbook: utils/update_user_repo.yml
  when: not ( update_user_repo_executed | default(false) | bool )

- name: Set flag
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: Set flag to indicate utility executed
      ansible.builtin.set_fact:
        apt_lock_status: true
        update_user_repo_executed: true
        update_inventory_executed: true
        inventory_validation_executed: true
        project_dir_status: true
        config_file_status: true

- name: Import playbook to install ROCm on nodes
  ansible.builtin.import_playbook: utils/rocm_installation.yml

- name: Verify Gaudi nodes
  ansible.builtin.import_playbook: utils/verify_intel_gaudi/verify_intel_gaudi_installation.yml

- name: Import playbook to set performance profile on nodes with Intel Gaudi accelerator
  ansible.builtin.import_playbook: utils/performance_profile/performance_profile.yml

- name: Configure security on nodes
  ansible.builtin.import_playbook: security/security.yml

- name: Import playbook to configure storage on nodes
  ansible.builtin.import_playbook: storage/storage.yml

- name: Execute slurm/kubernetes
  ansible.builtin.import_playbook: scheduler/scheduler.yml
