# Copyright 2025 Dell Inc. or its subsidiaries. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
---

- name: Set_fact for fetch omnia config credentials
  hosts: localhost
  connection: local
  tasks:
    - name: Set dynamic run tags including 'telemetry'
      ansible.builtin.set_fact:
        omnia_run_tags: "{{ (ansible_run_tags | default([]) + ['telemetry']) | unique }}"
        cacheable: true

- name: Invoke validate_config.yml to perform L1 and L2 validations
  ansible.builtin.import_playbook: ../input_validation/validate_config.yml

- name: Invoke get_config_credentials.yml
  ansible.builtin.import_playbook: ../utils/credential_utility/get_config_credentials.yml

- name: Include input project directory
  when: not project_dir_status | default(false) | bool
  ansible.builtin.import_playbook: ../utils/include_input_dir.yml

- name: Create provision container group
  ansible.builtin.import_playbook: ../utils/create_container_group.yml
  vars:
    oim_group: true

- name: Validate containers are running
  hosts: oim
  connection: ssh
  tasks:
    - name: Validate telemetry container is running
      ansible.builtin.include_role:
        name: telemetry_validation
        tasks_from: validate_telemetry_container.yml
      loop:
        - "activemq"
        - "idrac_telemetry_receiver"
        - "mysqldb"
      loop_control:
        loop_var: telemetry_container

- name: Validate telemetry input parameters
  hosts: localhost
  connection: local
  any_errors_fatal: true
  tasks:
    - name: Validate telemetry input parameters
      ansible.builtin.include_role:
        name: telemetry_validation
        tasks_from: validation_status_check.yml

# - name: Update Repositories/Registries on nodes
#   ansible.builtin.import_playbook: ../utils/update_user_repo.yml
#   when: not ( hostvars['127.0.0.1']['update_user_repo_executed'] | default(false) | bool )

- name: Configure oim ha node for telemetry
  hosts: oim_ha_node
  connection: ssh
  gather_facts: false
  roles:
    - oim_ha_node_config

- name: Render template for telemetry
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: Render template for telemetry
      ansible.builtin.include_role:
        name: service_node_config
        tasks_from: render_telemetry_template.yml

- name: Configure service nodes for telemetry
  hosts: sn_admin
  connection: ssh
  gather_facts: false
  roles:
    - service_node_config

- name: Deployment of telemetry container in service node
  hosts: sn_active
  connection: ssh
  gather_facts: false
  tasks:
    - name: Deployment of telemetry container in service node
      ansible.builtin.include_role:
        name: service_node_config
        tasks_from: pcs_container_deployment.yml

- name: Update prometheus configuration in OIM
  hosts: oim
  connection: ssh
  gather_facts: false
  tasks:
    - name: Render PCS template for telemetry
      ansible.builtin.include_role:
        name: service_node_config
        tasks_from: prometheus_config_update.yml

- name: Enable idrac telemetry in OIM
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: Render PCS template for telemetry
      ansible.builtin.include_role:
        name: idrac_telemetry

- name: Initiate telemetry collection on OIM
  hosts: oim
  connection: ssh
  gather_facts: false
  tasks:
    - name: Initiate telemetry collection
      ansible.builtin.include_role:
        name: idrac_telemetry
        tasks_from: trigger_telemetry_collection.yml
      when:
        - hostvars['localhost']['telemetry_idrac'] is defined
        - (hostvars['localhost']['telemetry_idrac'] | length > 0)

- name: Enable idrac telemetry in SN
  hosts: sn_active
  connection: ssh
  gather_facts: false
  tasks:
    - name: Render PCS template for telemetry
      ansible.builtin.include_role:
        name: idrac_telemetry

    - name: Initiate telemetry collection
      ansible.builtin.include_role:
        name: idrac_telemetry
        tasks_from: trigger_telemetry_collection.yml
      when:
        - telemetry_idrac is defined
        - (telemetry_idrac | length > 0)

- name: Telemetry report overview
  hosts: localhost, sn_active
  connection: ssh
  gather_facts: false
  vars:
    node_host: "{{ hostvars[inventory_hostname]['service_tag'] if inventory_hostname != 'localhost' else 'oim' }}"
    telemetry_report: |
          ---- Telemetry Report Overview ({{ node_host }}) ----
          IP with Telemetry not supported: {{ failed_idrac_count }}
          IPs with Telemetry Initiated: {{ filtered_idrac_count }}
  tasks:
    - name: Telemetry Report
      ansible.builtin.debug:
        msg: "{{ telemetry_report.splitlines() }}"

- name: Telemetry Report
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: Telemetry Report
      ansible.builtin.debug:
        msg: "Check the file at {{ telemetry_report_path_oim }} for detailed telemetry report."
