# Copyright 2025 Dell Inc. or its subsidiaries. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

---

- name: Check if Grafana container is running after deployment
  containers.podman.podman_container_info:
    name: "{{ grafana_container_name }}"
  register: grafana_container_status
  failed_when: false

- name: Stop and Remove Grafana container
  when: grafana_container_status.containers | length != 0
  block:
    - name: Stop the Grafana container
      containers.podman.podman_container:
        name: "{{ grafana_container_name }}"
        state: stopped
      failed_when: false

    - name: Remove Grafana container
      containers.podman.podman_container:
        name: "{{ grafana_container_name }}"
        state: absent
        force_delete: true

    - name: Remove Podman bind-mounted volumes for Grafana
      containers.podman.podman_volume:
        name: "{{ item.name }}"
        state: absent
      loop: "{{ grafana_podman_volumes }}"
      changed_when: false

    - name: Remove all listed secrets
      containers.podman.podman_secret:
        name: "{{ item }}"
        state: absent
      loop: "{{ grafana_secrets }}"
      changed_when: false

    - name: Remove Grafana directories from host
      ansible.builtin.file:
        path: "{{ item }}"
        state: absent
        force: true
      register: directory_deletion
      until: directory_deletion is not failed
      retries: "{{ max_retries }}"
      loop:
        - "{{ grafana_data_dir }}"
        - "{{ grafana_logs_dir }}"

    - name: Remove visualization ports on host firewalld
      ansible.posix.firewalld:
        port: "{{ item }}"
        state: disabled
        permanent: true
      loop: "{{ visualization_firewall_ports }}"
      changed_when: true

  rescue:
    - name: Grafana container removal failed
      ansible.builtin.fail:
        msg: "{{ grafana_container_name }} {{ container_removal_failure_msg }}"
