#  Copyright 2025 Dell Inc. or its subsidiaries. All Rights Reserved.
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.
---

- name: Check if {{ pcs_container_name }} container is running # noqa: name[template]
  containers.podman.podman_container_info:
    name: "{{ pcs_container_name }}"
  register: pcs_container_status
  failed_when: false

- name: Stop and Remove PCS container
  when: pcs_container_status.containers | length != 0
  block:
    - name: Unmanage omnia_core resource inside PCS container
      containers.podman.podman_container_exec:
        name: "{{ pcs_container_name }}"
        command: "pcs resource unmanage {{ omnia_container_name }}"
      register: pcs_unmanage_result
      failed_when: false

    - name: Stop the PCS container
      containers.podman.podman_container:
        name: "{{ pcs_container_name }}"
        state: stopped
      failed_when: false

    - name: Remove pcs container
      containers.podman.podman_container:
        name: "{{ pcs_container_name }}"
        state: absent
        force_delete: true

    - name: Stop omnia_pcs service
      ansible.builtin.systemd:
        name: "{{ pcs_container_name }}"
        state: stopped

    - name: Remove PCS service file
      ansible.builtin.file:
        path: "{{ pcs_service_file_path }}"
        state: absent

    - name: Reload systemd daemon
      ansible.builtin.systemd:
        daemon_reload: true

    - name: Remove PCS directory
      ansible.builtin.file:
        path: "{{ item }}"
        state: absent
        force: true
      register: directory_deletion
      until: directory_deletion is not failed
      retries: "{{ max_retries }}"
      with_items:
        - "{{ pcs_directory_cleanup }}"

    - name: Remove PCS-related ports on host firewalld
      ansible.posix.firewalld:
        port: "{{ item }}"
        state: disabled
        permanent: true
      loop: "{{ pcs_firewall_ports }}"
  rescue:
    - name: PCS container removal failed
      ansible.builtin.fail:
        msg: "{{ pcs_container_name }} {{ container_removal_failure_msg }}"
