#  Copyright 2025 Dell Inc. or its subsidiaries. All Rights Reserved.
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.
---

- name: Deployment of k8s telemetry service
  when:
    - hostvars['localhost']['idrac_telemetry_support']
    - hostvars['localhost']['federated_idrac_telemetry_collection']
  block:
    - name: Prerequisite checks for k8s telemetry service
      ansible.builtin.include_tasks: prereq_checks.yml

    - name: Configure k8s secrets
      ansible.builtin.include_tasks: secrets_creation.yml

    - name: Deployment of mysqldb pod
      ansible.builtin.include_tasks: mysqldb_deployment.yml

    - name: Deployment of prometheus pod
      ansible.builtin.include_tasks: prometheus_deployment.yml

    - name: Deployment of idrac-telemetry pod
      ansible.builtin.include_tasks: idrac_telemetry_deployment.yml
