# Copyright 2025 Dell Inc. or its subsidiaries. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
---

- name: Initialize variables
  ansible.builtin.set_fact:
    validation_status: true
    add_network_status: false
    reassignment_status: false
    provision_shared_library_path: "{{ provision_shared_library_path }}"

- name: Set_fact for omnia_config_credentials.yml variables
  ansible.builtin.set_fact:
    provision_password: "{{ hostvars['localhost']['provision_password'] }}"
    bmc_username: "{{ hostvars['localhost']['bmc_username'] }}"
    switch_snmp3_username: "{{ hostvars['localhost']['switch_snmp3_username'] }}"
    bmc_password: "{{ hostvars['localhost']['bmc_password'] }}"
    switch_snmp3_password: "{{ hostvars['localhost']['switch_snmp3_password'] }}"
    postgresdb_password: "{{ hostvars['localhost']['postgresdb_password'] }}"
  no_log: true

- name: Check if any tag is given
  ansible.builtin.assert:
    that:
      - ansible_run_tags | default(['all']) | difference(['all']) | length == 0
    fail_msg: "{{ ansible_tag_fail_msg }}"

# - name: Check if only management_layer tag is present
#   ansible.builtin.assert:
#     that:
#       - ansible_run_tags | default(['all']) | intersect(['management_layer']) | length == 1
#     fail_msg: "{{ ansible_invalid_tag_fail_msg }}"
#   when: "'all' not in ansible_run_tags"

- name: Validate provision container services status
  ansible.builtin.include_tasks: validate_provision_container.yml

- name: Include provision_validation_vars role vars
  ansible.builtin.include_vars: "{{ item }}"
  with_items: "{{ provision_validation_vars }}"

- name: Include vars for {{ oim_os }}
  ansible.builtin.include_vars: "{{ role_path }}/vars/{{ oim_os }}.yml"

- name: Include high_availabiliity variables
  ansible.builtin.include_tasks: include_high_availability_config.yml

- name: Include composable role data
  ansible.builtin.include_tasks: include_composable_roles_config.yml

- name: Include provision configuration variables
  ansible.builtin.include_tasks: include_provision_config.yml

- name: Include local_repo variables
  ansible.builtin.include_tasks: include_local_repo_config.yml

- name: Include telemetry config variables
  ansible.builtin.include_tasks: include_telemetry_config.yml

- name: Validate service_node repo
  ansible.builtin.include_tasks: validate_service_node_repo.yml
  when: service_role_required | default(false)

# - name: Validate local repo
#   ansible.builtin.include_tasks: validate_local_repo.yml

- name: Validate network interface type
  ansible.builtin.include_tasks: assign_network_interface.yml

- name: Validate the nic parameters
  ansible.builtin.include_tasks: validate_oim_nic.yml

- name: Validate network spec input
  ansible.builtin.include_tasks: validate_network_spec.yml

- name: Validate discovery parameters
  ansible.builtin.include_tasks: validate_discovery_params.yml

- name: Include vars for metadata
  ansible.builtin.include_vars: "{{ role_path }}/../../metadata_creation/vars/main.yml"

- name: Create metadata
  ansible.builtin.include_tasks: "{{ role_path }}/../../metadata_creation/tasks/main.yml"

- name: Validate provision parameters
  ansible.builtin.include_tasks: validate_provision_vars.yml

- name: Validate disk partition parameters
  ansible.builtin.include_tasks: validate_disk_partition_vars.yml
  with_items: "{{ disk_partition }}"

- name: Validate domain name
  ansible.builtin.include_tasks: validate_domain_name.yml

- name: Validate site_config.yml
  ansible.builtin.include_tasks: validate_site_config.yml

- name: Validate OFED and CUDA repo
  ansible.builtin.include_tasks: validate_ofed_cuda_repo.yml

- name: Validate AMDGPU and ROCm repo
  ansible.builtin.include_tasks: validate_amdgpu_rocm_repo.yml

- name: Validate racadm repo
  ansible.builtin.include_tasks: validate_racadm_repo.yml

# - name: Validate Broadcom repo
#   ansible.builtin.include_tasks: validate_broadcom_repo.yml

# - name: Validate Intel Gaudi repo
#   ansible.builtin.include_tasks: validate_intelgaudi_repo.yml
