#  Copyright 2025 Dell Inc. or its subsidiaries. All Rights Reserved.
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.
---

# Usage: fetch_software_config.yml
software_config_file: "{{ input_project_dir }}/software_config.json"
config_filename: "omnia_config.yml"
omnia_config_syntax_fail_msg: "Failed. Syntax errors present in omnia_config.yml. Fix errors and re-run playbook again."
software_config_syntax_fail_msg: "Failed. Syntax errors present in software_config.json. Fix errors and re-run playbook again."
ha_config_file: "{{ input_project_dir }}/high_availability_config.yml"
ha_config_syntax_fail_msg: "Failed. Syntax errors present in high_availability_config.yml. Fix errors and re-run playbook again."

# Usage: fetch_omnia_config.yml
deployment_false_msg: >
  None of the entries under '{{ cluster_type }}_k8s_cluster' have 'deployment' set to 'true'.
  Please update exactly one cluster under '{{ cluster_type }}_k8s_cluster' in omnia_config.yml with 'deployment: true'.
compute_service_k8s_true_fail_msg: "Both scheduler.yml and service_k8s_cluster.yml cannot be run together. Run only any one of playbook."
cluster_type_unknown_msg: "Neither compute_k8s_playbook nor service_k8s_playbook is set."

# Usage: validate_inventory.yml
empty_inventory_fail_msg: |
  "Failed. inventory not provided. Re-run playbook with inventory by providing -i inventory.
  Inventory support groups are slurm_control_node, slurm_node, login, kube_control_plane, kube_node, etcd, auth_server"
cluster_layout_path: "/opt/omnia/omnia_inventory/cluster_layout"
warning_wait_time: 30
inventory_warn_msg: |
  "[WARNING] Inventory not provided. Omnia generated inventory detected at {{ cluster_layout_path }}.
   If roles details are provided in roles_config.yml, the generated inventory will be used and proceeding."

# Usage: k8s_validations.yml
k8s_nfs_share: "/opt/omnia/kubespray/{{ hostvars['127.0.0.1']['cluster_var_name'] }}/{{ hostvars['127.0.0.1']['cluster_name'] }}"
file_mode: '0755'
file_perm: '0644'
invalid_kube_inventory_fail_msg: |
  "Failed. k8s software is present in software_config.json.
  Invalid inventory format, specify kube_control_plane, kube_node and etcd group in inventory and re-run playbook"
kube_one_node_validation_fail_msg: |
  "Failed. k8s software is present in software_config.json.
  There should be one entry for kube_control_plane in the inventory"
kube_control_plane_validation_fail_msg: |
  "Failed. k8s software is present in software_config.json.
  kube_control_plane group in inventory must have atleast one node."
kube_control_plane_ha_validation_fail_msg: |
  "Failed. k8s software is present in software_config.json.
  kube_control_plane group in inventory must have more than one node and total node count must be odd"
kube_ha_setup_warning_msg: |
  "[WARNING] To ensure a clear leader election in a Kubernetes High Availability (HA) setup,
  configure the cluster with an odd number of kube_control_plane and etcd nodes (e.g., 3, 5, or 7). Proceeding execution with provided nodes."
kube_nonha_setup_warning_msg: |
  "[WARNING] In a non-HA setup with multiple control plane nodes and a single etcd node,
  if the etcd node fails, the entire Kubernetes cluster could experience downtime.Proceeding execution with provided nodes."
kube_one_node_validation_success_msg: |
  "kube_control_plane exists in the inventory"
kube_node_validation_fail_msg: |
  "Failed. k8s software is present in software_config.json.
  At least one kube_node should be present in the inventory."
kube_node_validation_success_msg: "At least one kube_node exists in the inventory"
etcd_node_validation_fail_msg: |
  "Failed. k8s software is present in software_config.json.
  etcd group in inventory must have atleast one node and total node count must be odd."
etcd_node_validation_success_msg: "etcd should have odd number of nodes in the inventory"
unreachable_kube_control_plane_fail_msg: |
  "Failed. Unreachable node mentioned in inventory for kube_control_plane.
  Re-run playbook with reachable kube_control_plane."

# Usage: slurm_validations.yml
invalid_slurm_inventory_fail_msg: |
  "Failed. slurm software is present in software_config.json.
  Invalid inventory format, specify slurm_control_node, slurm_dbd and slurm_node group in inventory and re-run playbook."
slurm_one_node_validation_fail_msg: |
  "Failed. slurm software is present in software_config.json.
  There should be exactly one entry for slurm_control_node in the inventory."
slurm_one_node_validation_success_msg: |
  "One slurm_control_node exists in the inventory"
  slurm_node_validation_fail_msg: "Failed. slurm software is present in software_config.json.
  At least one slurm_node should be present in the inventory."
slurm_node_validation_success_msg: "At least one slurm_node exists in the inventory"
unreachable_slurm_control_node_fail_msg: |
  "Failed. Unreachable node mentioned in inventory for slurm_control_node.
  Re-run playbook with reachable slurm_control_node."
slurm_control_node_in_login_fail_msg: "Failed. Node mentioned in slurm_control_node group should not be present in login group"
slurm_control_node_in_node_fail_msg: "Failed. Node mentioned in slurm_control_node group should not be present in slurm_node group"
multiple_login_node_fail_msg: "Failed. Currently only one login node supported in inventory"
login_node_warning_msg: |
  "[WARNING] login group with ip for login node not present in the inventory.
  Proceeding execution with provided nodes"
slurm_node_validation_fail_msg: |
  "Failed. slurm software is present in software_config.json.
  There should be atleast one entry for slurm_node in the inventory."

# Usage: validate_inventory.yml
invalid_auth_server_inventory_fail_msg: |
  "Failed. openldap or freeipa software is present in software_config.json.
  Invalid inventory format, specify auth_sever group in inventory and re-run playbook."
auth_server_group_fail_msg: "Failed, auth_server group should contain exactly 1 node"
auth_server_group_success_msg: "Success, inventory file is valid"
auth_etcd_fail_msg: "Failed, etcd and auth_server nodes cannot be the same. Please fix
  the inventory file and re-run the playbook."
